---
kind: pipeline
type: kubernetes
name: Image Staging

platform:
    os: linux
    arch: arm

trigger:
  event:
  - push
  - tag

steps:
  - name: apply patches
    image: drone/git
    commands:
      - git submodule init
      - git submodule update --recursive
      - cp plugin.sh img
      - cd img
      - git apply --whitespace=fix --3way ../patches/*

  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:latest
    pull: always
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: drone-genuinetools-img
      tags: ${DRONE_BRANCH},unstable
      insecure_registry: true
    resources:
      requests:
        cpu: 1500
        memory: 750MiB

  - name: test
    pull: always
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:unstable
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: drone-genuinetools-img
      tags: ${DRONE_BRANCH},unstable
      insecure_registry: true
    resources:
      requests:
        cpu: 1500
        memory: 750MiB

---
kind: pipeline
type: kubernetes
name: Image Production

platform:
    os: linux
    arch: arm

trigger:
  event:
  - tag

depends_on:
  - Image Staging

steps:
  - name: apply patches
    image: drone/git
    commands:
      - git submodule init
      - git submodule update --recursive
      - cp plugin.sh img
      - cd img
      - git apply --whitespace=fix --3way ../patches/*

  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:unstable
    pull: always
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: drone-genuinetools-img
      auto_tag: true
      insecure_registry: true
    resources:
      requests:
        cpu: 2000
        memory: 750MiB

---
kind: pipeline
type: kubernetes
name: Notify Status

clone:
  disable: true

trigger:
  status:
  - success
  - failure

depends_on:
- Image Staging
- Image Production

platform:
  os: linux
  arch: arm

steps:
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      username: drone.io
      color: auto
      message: >
        <:genuinetools:857329283278438464> **{{repo.name}}**

        {{#success build.status}}
        :white_check_mark: {{build.event}} build {{build.number}} succeeded. Good job.
        {{else}}
        :warning: {{build.event}} build {{build.number}} failed. Fix me please.
        {{/success}}

        {{build.link}}

        **Branch:** {{commit.branch}} {{commit.tag}}

        **Message:** {{commit.message}}

---
kind: signature
hmac: 5ba667bf1949821c0ddbf270c4e9c553a60f94afe8c72b632fc2b51a40ba5c33

...
