---
kind: pipeline
type: kubernetes
name: Image Staging

platform:
    os: linux
    arch: arm

trigger:
  event:
  - push
  - tag

steps:
  - name: prepare
    image: drone/git
    commands:
      - git submodule init
      - git submodule update --recursive
      - cp plugin.sh img
      - ( cd img && git apply --whitespace=fix --3way ../patches/* )

  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:latest
    pull: always
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: drone-genuinetools-img
      context: img
      build_args: GIT_BRANCH=${DRONE_BRANCH},GIT_COMMIT=${DRONE_COMMIT},GIT_TAG=unstable
      tags: ${DRONE_BRANCH},unstable
      cache: true
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

  - name: test
    pull: always
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:unstable
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: drone-genuinetools-img
      context: img
      build_args: GIT_BRANCH=${DRONE_BRANCH},GIT_COMMIT=${DRONE_COMMIT},GIT_TAG=unstable
      tags: ${DRONE_BRANCH},unstable
      cache: false
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

---
kind: pipeline
type: kubernetes
name: Image Production

platform:
    os: linux
    arch: arm

trigger:
  event:
  - tag

depends_on:
  - Image Staging

steps:
  - name: prepare
    image: drone/git
    commands:
      - cp plugin.sh img
      - cd img
      - git apply --whitespace=fix --3way ../patches/*

  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img:unstable
    pull: always
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: drone-genuinetools-img
      context: img
      build_args: GIT_BRANCH=${DRONE_BRANCH},GIT_COMMIT=${DRONE_COMMIT},GIT_TAG=${DRONE_TAG}
      auto_tag: true
      cache: true
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

---
kind: signature
hmac: 764e6a1fda61976f28462cda3b6688aa7f24359869b83828a811a187a358ece1

...
